# Generated by Django 3.2.9 on 2021-11-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='goal',
            field=models.CharField(default=2500, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donations',
            name='raised',
            field=models.CharField(default=3000, max_length=10),
            preserve_default=False,
        ),
    ]
