# Generated by Django 3.2.9 on 2021-11-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
