# Generated by Django 3.2.9 on 2021-11-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20211123_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.TextField(max_length=30),
        ),
    ]
