# Generated by Django 3.2.9 on 2021-11-23 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_events_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Gallery', max_length=20)),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/%d')),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='thumbnail',
            field=models.ImageField(upload_to='events/%Y/%m/%d'),
        ),
    ]
