# Generated by Django 3.2.9 on 2021-11-26 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='number',
            new_name='phonenumber',
        ),
    ]
