# Generated by Django 3.2.9 on 2021-11-26 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_rename_number_contact_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phonenumber',
        ),
    ]
